config/routes.rb
Rails.application.routes.draw do
  root "static#welcome"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "signin", to: "sessions#new"
  post "signin", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  resources :sessions, only: [:new, :create, :destroy]
  resources :music_stores, only: [:index, :show]
  resources :customers, only: [:new, :show, :create]

  resources :instruments, only: [:index, :show] do
    resources :purchases, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :purchases
  has_many :instruments, through: :purchases
  has_many :music_stores, through: :purchases
  has_secure_password
  validates :name, presence: true, uniqueness: true
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  has_one :purchase
  belongs_to :music_store

  scope :rating, -> { where("year_made < 1979") }

  validates :name, :year_made, presence: true

  def self.available(music_store)
    instrument_ids_for_store = music_store.instruments.pluck(:id)
    purchased_instrument_ids_from_store = Purchase.where(music_store: music_store).pluck(:instrument_id)

    where(id: instrument_ids_for_store - purchased_instrument_ids_from_store)
  end
end

app/models/music_store.rb
class MusicStore < ApplicationRecord
  has_many :purchases
  has_many :instruments
  has_many :customers, through: :purchases

  validates :name, :address, presence: true
end

app/models/payment_type.rb
class PaymentType < ApplicationRecord
  belongs_to :purchases
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :customer
  belongs_to :music_store
  belongs_to :instrument

  validates :payment_type, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= Customer.find_by(id: session[:user_id])
  end

  def require_login
    return unless session[:user_id].nil?

    redirect_to root_path
  end
end

app/controllers/concerns/customers_controller.rb
class CustomersController < ApplicationController
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: %i[new create]

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(user_params)
    if @customer.save
      redirect_to @customer, notice: "Thanks for creating a login name, please sign in"
    else
      render :new, notice: "Name & Password do not match. Please try again"
    end
  end

  def show
    @customer = Customer.find(params[:id])
    redirect_to root_path unless session[:user_id].present?
  end

private

  def user_params
    params.require(:customer).permit(
      :name,
      :password
    )
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :require_login

  def index
    @instruments = Instrument.all
    @customer = current_user
    @instruments_ratings = Instrument.rating
  end

  def show
    @instrument = Instrument.find(params[:id])
  end

private

  def instrument_params
    params.require(:instrument)
          .permit(
            :instrument_type,
            :name,
            :make,
            :model,
            :color,
            :year_made
          )
  end
end

app/controllers/music_stores_controller.rb
class MusicStoresController < ApplicationController
  before_action :require_login

  def index
    @music_stores = MusicStore.all
    @customer = current_user
  end

  def new
    @music_store = MusicStore.new
  end

  def create
    @music_store = MusicStore.new(music_store_params)
    @music_store.customer_id = current_user.id
    if @music_store.save
      redirect_to music_stores_path
    else
      render :new
    end
  end

  def show
    @music_store = MusicStore.find(params[:id])
    @instruments = Instrument.available(@music_store)
  end

private

  def music_store_params
    params.require(:music_store)
          .permit(
            :name,
            :address
          )
  end
end

app/controllers/payment_types_controller.rb
class PaymentTypesController < ApplicationController
  def index
    @payment_types = PaymentType.all
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_instrument
  before_action :set_purchase, only: [:show]

  def index
    @purchases = @instrument.purchase
    @customer = current_user
  end

  def new
    @purchase = Purchase.new
    @customer = current_user
  end

  def show; end

  def create
    @purchase = Purchase.new(purchase_params)
    @purchase.instrument = @instrument
    @purchase.customer_id = session[:user_id]
    if @purchase.save
      redirect_to customer_path(session[:user_id])
    else
      # render error messages
      render :show
    end
  end

private

  def set_instrument
    @instrument = Instrument.find(params[:instrument_id])
  end

  def set_purchase
    @purchase = @instrument.purchases.find(params[:id])
  end

  def purchase_params
    params.require(:purchase)
          .permit(
            :music_store_id,
            :payment_type
          )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @customer = Customer.new
  end

  def create
    if (@customer = Customer.find_by(name: params[:customer][:name]))
      authenticated = @customer.authenticate(params[:customer][:password])
      if authenticated
        session[:user_id] = @customer.id

        redirect_to customer_path(@customer), notice: "Thanks for coming back, we appreciate it"
      else
        redirect_to signin_path, notice: "Name & Password do not match. Please try again"
      end
    else
      redirect_to root_path, notice: "Name & Password do not match. Please try again"
    end
  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def welcome; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payment_types_helper.rb
module PaymentTypesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/customers/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@customer) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/customers/show.html.erb
<h1>Thank you <%= "#{@customer.name}!" %> </h1>
<h2>Please click "continue" to see the inventory</h2>
<%= link_to "Continue", instruments_path %>
<br>
<br>
<br>
<br>
<%= link_to "Log Out", logout_path %>

app/views/instruments/index.html.erb
<% @instruments.each do |instrument| %>
  <h6> To learn more about the instrument, visit the instrument's music store link!</h6>
  <h4> Instrument Type: <%= instrument.instrument_type %> </h4>
  <h4> Instrument Make: <%= instrument.make %> </h4>
  <h4> Instrument Model: <%= instrument.model %> </h4>
  <h4> Instrument Location: <%= link_to instrument.music_store.name, music_store_path(instrument.music_store) %> </h4>
  <br>
<% end %>


<h3>Instruments with VINTAGE STATUS (Where the Instrument was made before 1980) </h3>

  <% @instruments_ratings.each do |instrument| %>
    <%= instrument.year_made %><br>
  <% end %>
<br>
<br>
<br>
<%= link_to "Log Out", logout_path %>

app/views/instruments/new.html.erb
<h1>Instruments NEW View Test</h1>

app/views/instruments/show.html.erb
<h1> instruments#show <h1>

<% @instruments.each do |instrument| %>
  <h4> Instrument Type: <%= instrument.instrument_type %> </h4>
  <h4> Instrument Year Made: <%= instrument.year_made %> </h4>
  <h4> Instrument Make: <%= instrument.make %> </h4>
  <h4> Instrument Name: <%= instrument.name %> </h4>
  <h4> Instrument Model: <%= instrument.model %> </h4>
  <h4> Instrument Color: <%= instrument.color %> </h4>
  <h4> Instrument Location: <%= link_to instrument.music_store.name, music_store_path(instrument.music_store) %> </h4>
  <br>
  <br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhrgRailsProjectMusicstore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/music_stores/index.html.erb
<h1>Music_Stores Index Page</h1>

<h1>Welcome to GIT YOUR GEETS Independent MusicStore</h1>
<h3>Wanna GIT A GEET?</h3>
<h4>Please, SignIn!</h4>
<%= form_tag "/signin" do %>
   <%= submit_tag "SignIn"%>
<% end %>
<br>

app/views/music_stores/new.html.erb
<h1>Welcome NEW PAGE for to MusicStore</h1>

app/views/music_stores/show.html.erb
<h3>Music Store: <%= @music_store.name %> </h3>
<p> Music Store Address: <%= @music_store.address %> </p>
<p>Instruments In Stock At <%= @music_store.name %> </p>
<ul>
  <% @instruments.each do |instrument| %>
    <li>
      <%= instrument.instrument_type %><br>
      <%= instrument.year_made %><br>
      <%= instrument.make %><br>
      <%= instrument.name %><br>
      <%= instrument.model %><br>
      <%= instrument.color %><br>
      <%= link_to "Purchase Instrument", new_instrument_purchase_path(instrument) %>
      <br>
      <br>
    </li>
    </li>
  <% end %>
  <%= link_to "Log Out", logout_path %>
</ul>

app/views/purchases/new.html.erb
<h4> So you'd like to purchase a GEET? </h4>

<h5>
  <%= "To purchase #{@instrument.year_made} #{@instrument.make} #{@instrument.name} #{@instrument.model} in #{@instrument.color}" %>
</h5>

<h5> Please provide select your payment type(s)</h5>

<br>
<br>

<%= form_for([@instrument, @purchase], url: instrument_purchases_path) do |f| %>
  <input type="hidden" name="purchase[music_store_id]" value="<%= @instrument.music_store_id %>" />
  <%= f.label :payment_type %>
  <%= f.collection_select :payment_type, ["cash", "debit", "credit", "check"], :to_s, :to_s, include_blank: false %>
  <%= f.submit %>
<% end %>

<br>
<br>

<%= link_to "Log Out", logout_path %>

app/views/purchases/show.html.erb
<h5> Thank you for purchasing a
<%= "#{@instrument.year_made} #{@instrument.make} #{@instrument.name} #{@instrument.model} in #{@instrument.color} !!"%><h5>
<h5> If you'd like to continue shopping, please click "continue shopping"</h5>
  <%= link_to "Continue Shopping", instruments_path %>
<br>
<br>
<br>
<br>
  <%= link_to "Log Out", logout_path %>